/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "Delay.h"
#include "OLED.h"
#include "servo.h"
#include "Key.h"

uint8_t key = 0;
double angle = 0;

int main(void)
{
 	OLED_Init();  /* Initialize the OLED display */
	Key_Init();   /* Initialize the key input */
	Servo_Init();   /* Initialize the servo */

	OLED_ShowString(1, 1, "Angle: "); // Display label on OLED

	for(;;)
	{
		key = Key_Scan(GPIO_Pin_1); // Scan for key input
		if(key == 1)
		{
			angle += 30;
			if(angle > 180) angle = 0;
		}
		Servo_SetAngle(angle);
		OLED_ShowNum(1, 8, (uint16_t)angle, 3); // Display the angle on OLED
	}
}
