/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "buzzer.h"
#include "light_sensor.h"

int main(void)
{
	Buzzer_Init();
	LightSensor_Init();
    /* Loop forever */
	for(;;)
	{
		if(LightSensor_Get() == 0) // Assuming active low
		{
			Buzzer_On();
		}
		else
		{
			Buzzer_Off();
		}
	}
}
