/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "UART.h"

#define MAX 128

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	OLED_Init();  /* Initialize the OLED display */
	UART_Init();  /* Initialize the UART */

	// UART_SendByte('A');
	// UART_SendArray((uint8_t *)"Hello, UART!\n", 13);
	// UART_SendString("UART Initialized Successfully!\n");
	// UART_SendNumber(12345, 5);
	printf("Num=%d\n", 666);
	char str[MAX] = "";
	sprintf(str, "Num=%d\r\n", 666);
	UART_SendString(str);
	UART_Printf("Num=%d\r\n", 666);
	printf("你好，世界\r\n");

    /* Loop forever */

	for(;;)
	{
	}
}
