/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "UART.h"
#include "Key.h"
#include "stm32f10x_gpio.h"

#define MAX 128

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	Key_Init();  /* Initialize the key input */
	OLED_Init();  /* Initialize the OLED display */
	OLED_ShowString(1, 1, "TxPacket:");
	OLED_ShowString(3, 1, "RxPacket:");
	UART_Init();  /* Initialize the UART */

	uint8_t packet[PAK_SIZE] = {1, 2, 3, 4};

    /* Loop forever */

	for(;;)
	{
		if (Key_Scan(GPIO_Pin_1))
		{
			for (int i = 0; i < PAK_SIZE; i++)
			{
				packet[i]++; // 修改数据
			}
			UART_SendPacket(packet, PAK_SIZE);
			for (int i = 0; i < PAK_SIZE; i++)
			{
				OLED_ShowHexNum(2, 1 + i * 3, packet[i], 2);
			}
		}
		if (UART_GetRxFlag())
		{
			for (int i = 0; i < PAK_SIZE; i++)
			{
				OLED_ShowHexNum(4, 1 + i * 3, UART_RxPacket[i], 2);
			}
		}
	}
}
