/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "UART.h"

#define MAX 128

uint8_t RxData;

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	OLED_Init();  /* Initialize the OLED display */
	UART_Init();  /* Initialize the UART */

	OLED_ShowString(1, 1, "RxData: ");

    /* Loop forever */

	for(;;)
	{
		if (UART_GetRxFlag())
		{
			RxData = UART_GetRxData();
			UART_SendByte(RxData);
			OLED_ShowHexNum(1, 9, RxData, 2); // 在OLED上显示接收到的字符
		}
	}
}
