/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"

int main(void)
{
 	OLED_Init();  /* Initialize the OLED display */

	OLED_ShowChar(1, 1, 'A'); /* Display character 'H' at (0,0) */
	OLED_ShowString(1, 3, "Hello, STM32!"); /* Display string at (0,1) */
	OLED_ShowNum(2, 1, 12345, 5); /* Display number at (1,0) */
	OLED_ShowSignedNum(2, 7, -66, 2); /* Display signed number at (1,1) */
    OLED_ShowHexNum(3, 1, 0xAA55, 4); /* Display hexadecimal number at (2,0) */
	OLED_ShowBinNum(4, 1, 0b10110, 5); /* Display binary number at (2,1) */

	OLED_Clear(); /* Clear the display */
	
	for(;;);
}
