/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "count_sensor.h"

int main(void)
{
	OLED_Init();
	CountSensor_Init();
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);

	OLED_ShowString(1, 1, "Count: ");

    /* Loop forever */
	for(;;)
	{
		OLED_ShowNum(1, 8, CountSensor_GetCount(), 5);
	}
}
