/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "UART.h"
#include "stm32f10x_gpio.h"
#include "LED.h"
#include <string.h>

#define MAX 128

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	OLED_Init();  /* Initialize the OLED display */
	OLED_ShowString(1, 1, "TxPacket:");
	OLED_ShowString(3, 1, "RxPacket:");
	UART_Init();  /* Initialize the UART */
	LED_Init();   /* Initialize the LEDs */

	uint8_t packet[MAX] = {1, 2, 3, 4};

    /* Loop forever */

	for(;;)
	{
		if (UART_RxFlag) // 检查是否有新数据
		{
			OLED_ShowString(4, 1, "                "); // 清除旧数据
			OLED_ShowString(4, 1, UART_RxPacket); // 显示接收到的数据
			if(strcmp(UART_RxPacket, "LED_ON") == 0)
			{
				LED_On(GPIO_Pin_0 | GPIO_Pin_2);
				UART_SendString("LED_ON_OK\n");
				OLED_ShowString(2, 1, "                ");
				OLED_ShowString(2, 1, "LED_ON_OK");
			}
			else if(strcmp(UART_RxPacket, "LED_OFF") == 0)
			{
				UART_SendString("LED_OFF_OK\n");
				OLED_ShowString(2, 1, "                ");
				OLED_ShowString(2, 1, "LED_OFF_OK");
				LED_Off(GPIO_Pin_0 | GPIO_Pin_2);
			}
			else
			{
				UART_SendString("UNKNOWN_CMD\n");
				OLED_ShowString(2, 1, "                ");
				OLED_ShowString(2, 1, "UNKNOWN_CMD");
			
			}
			UART_RxFlag = 0; // 清除接收标志
		}
	}
}
