/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"

#define DELAY_MAX 200000

int main(void)
{
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
	GPIO_InitTypeDef GPIO_InitStructure;
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IPD;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_1;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	bool volatile flag0 = GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0);
	uint32_t volatile count = 0;
	/* Loop forever */
	while (1)
	{
		GPIO_WriteBit(GPIOA, GPIO_Pin_1, GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0) ? Bit_RESET : Bit_SET);
		bool volatile flag1 = GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0);
		if (flag0 != flag1)
		{
			count++;
			flag0 = flag1;
		}
		
	}
}
