/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "Delay.h"
#include "OLED.h"
#include "PWM.h"
#include "IC.h"

int main(void)
{
 	OLED_Init();  /* Initialize the OLED display */
	PWM_Init();   /* Initialize the PWM for controlling brightness */
	IC_Init();    /* Initialize the Input Capture for frequency measurement */

	OLED_ShowString(1, 1, "Freq: 00000Hz");
	OLED_ShowString(2, 1, "Duty: 00%");
	PWM_SetPrescaler(720 - 1); // Frep = 72M / (PSC + 1) / 100 = 1kHz
	PWM_SetCompare1(50); // Duty = CCR / 100 = 50%
	
	for(;;)
	{
		OLED_ShowNum(1, 7, IC_GetFreq(), 5); // Display the measured frequency on the OLED
		OLED_ShowNum(2, 7, IC_GetDuty(), 2); // Display the measured duty cycle on the OLED
	}
}
