/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "Delay.h"
#include "OLED.h"
#include "PWM.h"

uint8_t brightness = 0; // Variable to hold the current brightness level

int main(void)
{
 	OLED_Init();  /* Initialize the OLED display */
	PWM_Init();   /* Initialize the PWM for controlling brightness */
	
	for(;;)
	{
		while(brightness < 100)
		{
			PWM_SetDutyCycle(brightness);
			brightness++;
			Delay_ms(10); // Add a small delay to make the breathing effect visible
		}
		while(brightness > 0)
		{
			PWM_SetDutyCycle(brightness);
			brightness--;
			Delay_ms(10); // Add a small delay to make the breathing effect visible
		}
	}
}
