/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "Delay.h"
#include "OLED.h"
#include "motor.h"
#include "key.h"
#include "rotary_encoder.h"

int16_t speed = 0;

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);

 	OLED_Init();  /* Initialize the OLED display */
	Motor_Init();  /* Initialize the motor control */
	Key_Init();    /* Initialize the key input */
	RotaryEncoder_Init();

	OLED_ShowString(1, 1, "Speed: "); // Display label on OLED

	for(;;)
	{
		speed += RotaryEncoder_GetCount() * 20;
		if (speed > 100) {
			speed = 100; // Limit speed to 100
		} else if (speed < -100) {
			speed = -100; // Limit speed to -100
		}
		Motor_SetSpeed(speed);
		OLED_ShowSignedNum(1, 8, (int32_t)speed, 3); // Display the speed on OLED
	}
}
