/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "AD.h"

uint16_t ad_value = 0;

int main(void)
{
 	OLED_Init();  /* Initialize the OLED display */
	AD_Init();   /* Initialize the ADC */

	OLED_ShowString(1, 1, "AD Value: "); /* Display static text on the OLED */
	for(;;)
	{
		ad_value = AD_GetValue(); /* Get the current ADC value */
		OLED_ShowNum(1, 11, ad_value, 4); /* Display the ADC value on the OLED */
	}
}
