/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f10x.h"
#include <stdint.h>
#include "LED.h"
#include "Key.h"

int main(void)
{
	LED_Init();
	Key_Init();
    /* Loop forever */
	for(;;)
	{
		if (Key_Scan(GPIO_Pin_11)) // Assuming Key is connected to PB11
		{
			LED_Toggle(GPIO_Pin_2); // Turn on LED connected to PA2
		}
		if (Key_Scan(GPIO_Pin_1)) // Assuming another Key is connected to PB1
		{
			LED_Toggle(GPIO_Pin_0); // Turn on another LED connected to PA0
		}
	}
}
