/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "misc.h"
#include "stm32f10x.h"
#include "OLED.h"
#include "stm32f10x_tim.h"
#include "timer.h"
#include "encoder.h"
#include "Delay.h"

int16_t speed = 0;

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	
 	OLED_Init();  /* Initialize the OLED display */
	OLED_ShowString(1, 1, "Speed: "); /* Display character 'H' at (0,0) */
	Timer_Init(); /* Initialize the timer */
	Encoder_Init(); /* Initialize the encoder */

	for(;;)
	{
		OLED_ShowSignedNum(1, 8, speed, 5);
		// OLED_ShowNum(2, 6, TIM_GetCounter(TIM2), 5);
	}
}

void TIM2_IRQHandler(void)
{
	if (TIM_GetITStatus(TIM2, TIM_IT_Update) != RESET)
	{
		speed = Encoder_Get();
		TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
	}
}
