/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "OLED.h"
#include "rotary_encoder.h"

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);

	OLED_Init();
	RotaryEncoder_Init();

	OLED_ShowString(1, 1, "Count: ");

	int16_t num = 0;
    /* Loop forever */
	for(;;)
	{
		num += RotaryEncoder_GetCount();
		OLED_ShowSignedNum(1, 8, num, 5);
	}
}
